### ISSUE TITLE
ENH: integrate pygeos.STRtree spatial index

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1404]
Thanks to the great work of @adriangb, we are able to use pygeos' STRtree (if pygeos is installed) instead of rtree for spatial indexing operations.

Keeping track of the concrete (short-term)  to do items to finalize initial integration into geopandas. Short term, we want to refactor the geopandas internals somewhat so we can transparently use rtree or pygeos in the different functions in geopandas that use the `sindex`. Longer term, we want to make this more flexible / more general, but that is discussed in https://github.com/geopandas/geopandas/issues/1344

- [x] Add the ability to dynamically chose a spatial index implementation based on the `compat.USE_PYGEOS` flag and implement a wrapper around `pygeos.strtree` that gives it the same interface as the existing `rtree` (i.e. a `intersection` method) -> done in #1343
- [x] Add `query`/`quer_bulk` implementation for the the rtree-based sindex that is compatible with the methods from pygeos.STRtree -> #1401
- [x] Start using `query` / `query_bulk` internally in geopandas:
  - [x] `sjoin` -> #1421
  - [x] `overlay` -> #1428
  - [x] `clip` -> #1427
- [x] Fix error handling -> #1438

**Comment by adriangb** [comment]
@jorisvandenbossche can you please update the first post with #1428, #1421 and #1427?

**Comment by jorisvandenbossche** [comment]
Done!

**Comment by adriangb** [comment]
#1428 is done as well

**Comment by adriangb** [comment]
Adding #1438

**Comment by jorisvandenbossche** [comment]
OK, all is done here, closing.
