### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1776]
It is high time to do a next release! So opening this issue to start tracking it.

Milestone: https://github.com/geopandas/geopandas/milestone/14

**Comment by martinfleis** [comment]
Here's the list of PRs I'd like to see in 0.9. There may be some more but these are almost ready or needed.

PRs to finalize documentation revamp:

- [ ] DOC: documentation pages, ecosystem  #1759 
- [ ] DOC: first pass on the Introduction to GeoPandas #1757
- [ ] DOC: documentation improvements #1750
- [ ] DOC: document sindex API #1749
- [ ] DOC: use Jupyter examples via nbsphinx gallery #1731

Plus binary ops are documented as part of this PR:
- [ ] ENH: add a keyword to control alignment in binary operations and predicates #1668

Release related:
- [ ] GHA: Automatic release to PyPI #1578

Enhancements:
- [ ] ENH: add GeoSeries.z attribute #1773
- [ ] Integrate to/from wkt/wkb functions into public API #1710
- [ ] ENH: Make the id property in to_json optional #1637
- [ ] ENH: add option to remove bracket from mapclassify legend #1605
- [ ] ENH: Add GeoPlot accessor #1465

Bugs:
- [ ] BUG: Override shift in GeometryArray to preserve CRS #1744
- [ ] Fix compatilibilty with numpy 1.20.0 #1729

**Comment by jorisvandenbossche** [comment]
Adding "BUG: Plotting empty geometries generates a Type Error (shapely only) #1572" to the list, since that's a regression it would be good to fix.

**Comment by QuLogic** [comment]
I'd like to retire `descartes` with #1677, so cc'ing on the release progress.

**Comment by martinfleis** [comment]
@QuLogic That PR is already merged and will be part of 0.9, which in turn will no longer depend on `descartes`.

**Comment by martinfleis** [comment]
Just head up that readthedocs is broken at the moment since I apparently expected #1731 to be in while doing #1757 (therefore we don't pass proper environment now). Should fix itself once #1757  is merged.

**Comment by jorisvandenbossche** [comment]
I was looking at that PR as we speak. Let's just give it a go then ;)

**Comment by jorisvandenbossche** [comment]
I moved most of the issues/PRs labeled with the 0.9 milestone that are not listed above to the next 0.10 milestone

**Comment by martinfleis** [comment]
@jorisvandenbossche  Unless you want to go forward with #1831, I think we're ready to go! 🎉

**Comment by martinfleis** [comment]
Ah, let me just quickly hide Roadmap from docs, it is empty at the moment https://geopandas.readthedocs.io/en/latest/about/roadmap.html.

**Comment by jorisvandenbossche** [comment]
That issue is only relevant for development versions, so that can be dealt with after the release!

Let's just check the latest doc builds, and binder, etc

**Comment by martinfleis** [comment]
- [ ] [GeoPlot example](https://geopandas.readthedocs.io/en/latest/gallery/plotting_with_geoplot.html) raises an error (also locally)
- [ ] Plotting API docs is broken https://geopandas.readthedocs.io/en/latest/docs/reference/geodataframe.html#plotting
- [ ] Pandas plots are broken https://geopandas.readthedocs.io/en/latest/docs/user_guide/mapping.html#pandas-plots

Regarding GeoPlots, it seems an issue with geoplot so I'd remove the faulty example for now.

**Comment by jorisvandenbossche** [comment]
The binder link is now working (tested the introduction page, and 1 of the examples)

>  Pandas plots are broken https://geopandas.readthedocs.io/en/latest/docs/user_guide/mapping.html#pandas-plots

Hmm, that's caused by my GeoDataFrame.apply fix, taking a look

**Comment by jorisvandenbossche** [comment]
Better now: https://geopandas.readthedocs.io/en/latest/docs/reference/geodataframe.html#plotting

**Comment by martinfleis** [comment]
I think we'll have to eventually figure out that plotting docstring differently. Now we don't have a signature and parameters include `df` (since it is a docstring of `plot_dataframe` function). Do you want me to have a look at it today/tomorrow or shall we just ship it as it is and deal with it later?

**Comment by QuLogic** [comment]
Please be sure to check any plotting with Matplotlib 3.4.0rc1.

**Comment by martinfleis** [comment]
@QuLogic We run our tests with master matplotlib (3.3.4+2484.g2e248f522 atm). I guess we should be okay then? Or should I try to run CI explicitly with 3.4.0rc1?

**Comment by jorisvandenbossche** [comment]
> Now we don't have a signature and parameters include df (since it is a docstring of plot_dataframe function)

That was already the case before as well: https://geopandas.readthedocs.io/en/v0.8.2/reference.html#geopandas.GeoDataFrame.plot (so I don't think it is much worse right now than what we had before) 
For `df` being in the list of parameters, that's actually just somethin we can remove in the `plot_dataframe` docstring, since that method is not public.

**Comment by QuLogic** [comment]
> @QuLogic We run our tests with master matplotlib (3.3.4+2484.g2e248f522 atm). I guess we should be okay then? Or should I try to run CI explicitly with 3.4.0rc1?

Ah, I missed that test env; that should be fine, I think for now. Though it has branched off, I don't think there's too much difference yet.

**Comment by martinfleis** [comment]
> For df being in the list of parameters, that's actually just somethin we can remove in the plot_dataframe docstring, since that method is not public.

#1860

With that, I am fine with keeping the rest as it is for now.

**Comment by jorisvandenbossche** [comment]
Thanks!

Then I think we should be ready to go?

**Comment by martinfleis** [comment]
Yes! Ship it to the world!

**Comment by martinfleis** [comment]
Just add a date to changelog ;).

**Comment by jorisvandenbossche** [comment]
Yes ;) -> https://github.com/geopandas/geopandas/commit/ec4c6805d1182f846b9659345a5e66fa7c7afac7

**Comment by jorisvandenbossche** [comment]
And the workflow did its job: https://github.com/geopandas/geopandas/releases/tag/v0.9.0, https://pypi.org/project/geopandas/#files

Will send out announcements tomorrow when conda-forge is available

**Comment by martinfleis** [comment]
Thanks a lot @jorisvandenbossche. Esp. for such a strong finish ;).

Closing 🎉

**Comment by jorisvandenbossche** [comment]
And thank *you* for ensuring all PRs were already reviewed! ;)

**Comment by jorisvandenbossche** [comment]
And we shouldn't wait that long next time .. (or did we say that already before as well? ;))
