### ISSUE TITLE
GeoPandas 1.0 release

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3201]
An issue to track the remaining tasks we'd like to finish before GeoPandas 1.0.

The roadmap says:

- [x] Fully vectorized geometry engine (done in #2691)
- [x] Feature parity with shapely (tracked in #2010)
- [x] Clarity of the API (probably primarily #3007 and some finished deprecations)
- [x] Pruned dependencies (GDAL is optional, PROJ not yet - #2077)

Explicit to-do I think we should ensure is in:

- [x] #2010
- [x] pyogrio engine as a default
- [x] pyogrio functionality exposed from geopandas (e.g. `list_layers` #2837)
- [x] soft-dependency on pyproj (#2077)
- [x] #2144 (#498)

Discussion required:

- [ ] updated roadmap for post-1.0
- [x] #1832

And finally, the milestone itself containing the remaining issues/PRs:

- https://github.com/geopandas/geopandas/milestones/1.0

The release is currently planned for March 31, 2024. If we go a bit beyond that is fine I guess but would try to ensure we don't push it too far.

**Comment by m-richards** [comment]
I think it would be good to try and solve #1038 for 1.0 - the discussion there is old but the proposed solution is potentially breaking, so better to try and include and resolve for 1.0.

Probably also worth revisting / deciding whether to action https://github.com/geopandas/geopandas/issues/3019 /  https://github.com/geopandas/geopandas/issues/1975
(not sure if I will be able to make the scheduled meeting tomorrow/ today)

**Comment by kylebarron** [comment]
I'd be motivated to get https://github.com/geopandas/geopandas/issues/3156 in to 1.0 if we can agree on a proposed API. I'd be happy to make a PR

**Comment by martinfleis** [comment]
@kylebarron I don't know much about that but if you can get @jorisvandenbossche on board I won't object.

**Comment by martinfleis** [comment]
I suggest the following release plan:

Start with `1.0-alpha1 ` by the end of March that contains all the API-related changes but not necessarily all the bugfixes and enhancements. For that, I believe we need 

- [ ] #3223 
- [ ] #3212

Then, ideally by mid April, we could do `1.0-rc1` that shall contain the enhancements and deprecations and cut final 1.0 by end of April. That should give people enough time to test against 1.0 before it is released and provide feedback if needed. It should also give us enough time to finish what needs to be finished as end of March is unrealistic at this point. Thoughts?

**Comment by martinfleis** [comment]
The last thing that touches the existing API in some way is #3190. Once we get that in, I propose cutting `1.0-alpha1`.

**Comment by martinfleis** [comment]
I am planning to cut `1.0.0-alpha1` tonight as we're already a bit behind the anticipated schedule. 

Next milestone is `rc1` with all the new functionality. I suppose it will be pushed to the end of April, with 1.0 coming (optimistically) in early May. We do have a hard deadline 24/5 due to GeoPython starting a few days after that.

**Comment by martinfleis** [comment]
It is out! 

- https://github.com/geopandas/geopandas/releases/tag/v1.0.0-alpha1
- https://pypi.org/project/geopandas/1.0.0a1/

I wrote a short blog post with some highlights - https://martinfleischmann.net/geopandas-1.0-is-coming.-what-will-change/

**Comment by m-richards** [comment]
@martinfleis just fyi in your summary blog post, there's a typo in the fiona to pyogrio migration guide link, latert-> latest I think

**Comment by martinfleis** [comment]
@m-richards good catch! The typo was not the only issue, #3206 was not merged :D. I was writing that last week, assuming it will be in.

**Comment by martinfleis** [comment]
All good now - https://geopandas.org/en/latest/docs/user_guide/fiona_to_pyogrio.html.

**Comment by martinfleis** [comment]
> As an aside, I wonder if it'd be good to consider reorganising the docs pages for these "all geometries together" apis so they sit collectively under one heading, to make it clearer at a glance we've made a distinction about how they api should map to a geoseries, and it's not just verbatim porting of shapely

@m-richards's comment from #3273 - we should look at that once all shapely parity PRs are in.

**Comment by jorisvandenbossche** [comment]
Shall we try to do an RC early coming week?

**Comment by martinfleis** [comment]
@jorisvandenbossche can we get remaining new features in? Would be nice, given we need 1.0 ideally by the end of the next week to have it our for GeoPython.

**Comment by jorisvandenbossche** [comment]
The main remaining features that I am focusing on are the GeoParquet / GeoArrow related ones.

Further, I think all shapely-parity related PRs are in? 
Are there other issues/PRs from the milestone (https://github.com/geopandas/geopandas/milestone/4) that we should still give some priority?

Given that we still made a few API changes, would it be helpful to do another pre-release now to at least get _some_ testing of it? 
(the geoparquet/geoarrow are generally new and so should in theory not break existing code)

**Comment by martinfleis** [comment]
I would like to get #3231 as it is ready.  Apart from all of the GeoArrow and GeoParquet stuff, I have no strong feelings about the rest and wouldn't mind moving it to 1.1.

**Comment by jorisvandenbossche** [comment]
I think the main issue that is left (that has impact on API, and is not just an enhancement of bug fix) is https://github.com/geopandas/geopandas/issues/3312

We still have a bunch of other issues labeled with the milestone https://github.com/geopandas/geopandas/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0, but we will have to bump most of them to 1.1, I think.

I think we should try to do an RC this week. We could do that with keeping the change discussed in https://github.com/geopandas/geopandas/issues/3312 to get more feedback on that, but on the other hand in case we would have consensus of reverting it for `GeoDataFrame(..)`, it would be a bit stupid to have people that test the RC to update their code potentially wrongly. So ideally we would resolve that discussion this week, I think.

**Comment by jorisvandenbossche** [comment]
I am planning to cut `1.0.0rc0` later today

**Comment by martinfleis** [comment]
Thank you @jorisvandenbossche!

**Comment by EwoutH** [comment]
Congratulations on the 1.0 release!
